name:                hasql
version:             0.1.0.0
github:              "shraiysh/hasql"
license:             BSD3
author:              "Shraiysh Vaishay"
maintainer:          "cs17btech11050@iith.ac.in"
copyright:           "Copyright 2019 Shraiysh Vaishay"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/shraiysh/hasql#readme>

dependencies:
- base >= 4.7 && < 5
- text
- parsec

library:
  source-dirs: src

executables:
  hasql-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hasql

tests:
  hasql-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hasql
